services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:80"

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: wagtail
      POSTGRES_DB: wagtail_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
